FlowFuse/helm

- flowforge-container/Dockerfile
- node-red-container/Dockerfile
Force nr-launcher to use the Node-RED install from the base Docker container.
Also label the forge app container
> Fix version of NR available to Launcher

- build-containers.sh
- helm/flowforge/Chart.yaml
- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/values.schema.json
Part of https://github.com/flowforge/flowforge/issues/464
> Start of adding the broker

- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
Adding in some custom changes to production FF Cloud config file to the standard helm chart to make rebuilding easier
> Add plausible config

- build-containers.sh
- helm/flowforge/Chart.yaml
This bumps the versions that are not currently covered by  the prepare-release script
> Bump version for 0.8.0

- helm/flowforge/templates/broker.yaml
This adds a HTTP endpoint for the ALB to run healthchecks against
This is because I noticed that the broker WebSocket endpoint was failing healthcheck when looking for the problem with https://github.com/flowforge/flowforge-nr-project-nodes/issues/14
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#healthcheck-path
> Add Health Check URL for MQTT broker

- .github/workflows/build-containers.yml
This lets us use docker buildx to build multiplatform containers and apply some better rules to the tagging
https://github.com/docker/login-action
https://github.com/docker/metadata-action
https://github.com/docker/setup-qemu-action
https://github.com/docker/setup-buildx-action
https://github.com/docker/build-push-action
> Move to docker GH actions

- flowforge-container/Dockerfile
- node-red-container/Dockerfile
This is part of the work needed to move to GH npm repo for nightly builds
> Use GH token to auth if using custom repo

- node-red-container/package.json
They are already dependencies of the launcher
closed https://github.com/flowforge/helm/issues/55
> Remove flowforge nodes from /data/package.json

- helm/flowforge/README.md
Make it clear that the helm chart defaults expects 2 nodes in the cluster.
More instructions in the Kubernetes install instructions in https://github.com/flowforge/flowforge/pull/1229 on how to run on single node cluster
> Update helm chart readme about node selectors

- helm/flowforge/templates/configmap.yaml
- helm/flowforge/templates/file-storage.yml
make sure the file-server template formats properly
Also fix a line break in the telemetry section of the flowforge config map
> Fix indentation in file-server.yml

- .github/workflows/build-containers.yml
- flowforge-device-agent/Dockerfile
- flowforge-device-agent/README.md
Like the other images, the device agent might be run in a container. This change makes it easier to achieve this for our customers.
> Docker: Publish images for the device agent

- flowforge-container/Dockerfile
Alpine now sets /usr/bin/python to point to python3 so no need to do it ourselves
> No need to symlink python3 anymore

- helm/flowforge/README.md
- helm/flowforge/templates/file-storage.yml
- helm/flowforge/templates/job-upgrade-db.yaml
- helm/flowforge/templates/network-policy.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
Adds support for the persistent context to the helm chart
Includes a job to add the extra database to the locally provisioned instance of postgresql
> Add context store provisioning

- helm/flowforge/templates/job-upgrade-db.yaml
If helm upgrade was run twice this DB upgrade job would fail, while not a problem it left a old job in the pod list.
The script now tests if the database already exists before trying to create it.
This was raised in flowforge/flowforge#1524
> Allow upgrade DB script to run without failing

- node-red-container/Dockerfile-2.2.x
The 2.2.3 based stacks are currently built on the default 2.2.3 container which is based on NodeJS 14.
The FlowForge Launcher now contains code that depends on NodeJS 16
> Bump 2.2.3 container to NodeJS 16 base

- .github/workflows/build-containers.yml
Prevents helm chart publish until all containers are built and published
> Wait for containers to build before publish helm

- helm/flowforge/values.yaml
Typo fix for default context db hostname
> Fix missing `s` in default context host

- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
- test/customizations.yml
- test/unit/setup.js
Adds configuration option for posthog host
#106 
- [-] Changes `flowforge.yml`?
- [-] Issue/PR raised on `flowforge/helm` to update ConfigMap Template
- [-] Issue/PR raised on `flowforge/CloudProject` to update values for Staging/Production
- [-] Includes a DB migration? -> add the `area:migration` label
> Add posthog apihost to config

- helm/flowforge/templates/configmap.yaml
extra `-` was removing all white space including line break
> Fix line break in telemetry

- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
- test/customizations.yml
Adds `device_price` and `device_product` as *optional* config properties.
Ref: https://github.com/flowforge/admin/issues/145
> Add device product/price to config map

- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/service-ingress.yaml
While deploying to production I noticed that these were still present and no longer required.
> Remove hard coded ingress annotations for AWS

- .github/workflows/build-containers.yml
Syncs the maintenance branch to match main on a minor release (x.y.0)
NA
> Resync maintenance branch on release

- node-red-container/Dockerfile
- node-red-container/Dockerfile-2.2.x
- node-red-container/Dockerfile-3.1
Some nodes require the HOME env var to be set, this ensures it's always set in the container
Opted for /usr/src/node-red as that matches the entry in the /etc/passwd file.
Discovered via a HubSpot Ticket
> Add HOME env var

- helm/flowforge/templates/job-upgrade-db.yaml
With a name of release different from _flowforge_ the job _xxx-db-upgrade_ can't find _xxx-configMap_ and loop with fails
This PR try to fix it
> Fix Release.Name in job-upgrade-db

- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/service-ingress.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
We tried to deploy flowforge on AWS and Azure K8s cluster, and found that on both platforms it requires custom annotations to work with vendor Ingress controllers. 
This PR:
* Adds ability to set platform specific `Ingress` settings
* Documents new values in schema
* Adds dummy values to `values.yaml` to make the file formally valid against the schema
All changes are backward compatible
> Ingress settings for Flowforge in K8s

- helm/flowforge/README.md
- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/service-account.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
Multiple changes in FlowForge helm, all are optional.
FlowForge helm edits: 
1. **Editors**: optional service account provisioning*. 
2. **Broker**: propagate ingress definitions to broker helm. 
3. **values.yaml**: remove secrets from referent `values.yaml`, adding ref for `Editors default service account definition`. 
4. **README.md**: update with IAM section.
*Note that by "default" here meant that all Editor instances will be provisioned with this service account linked.
> We have a need and the plan for multiple IAM support, per Project, as a part of Project Configuration with the ability to change IAM binding (likewise the stack can be changed).
[FlowForge helm: option to provision default service account for editors. broker: derive the ingress definitions from values.yaml. cluster …
> FlowForge helm: 1. Editors: service account. 2. Broker: propagate ingress. 3. README

- helm/flowforge/templates/service-account.yaml
@elenaviter I've had to revert the renaming of the ClusterRole because it breaks upgrades.
We can look at this again after the release this week
We can not change the name of an already created ClusterRole as it breaks upgrades.
> Revert create-pod Role name

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/nodered-container.yml
Add the possibility to deploy flowforge container to the stage environment.
> Add possibility to deploy flowforge container to stage environment

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
Disable production container images build due to:
* we do not do automatic production deployments atm
* github does not allow to set custom timeout for deployment approvals for a particular environment (default: 30 days)
* we do not want to manually reject production deployments
> Disable production containers build

- .github/workflows/nodered-container.yml
- node-red-container/Dockerfile
- node-red-container/Dockerfile-3.1
This updates the Node-RED container images to include 3.1.0.
- Pin `Dockerfile` to `3.0.2` rather than `latest`
- Update `Dockerfile-3.1` to use release container, not dev stream container
- Update container workflow to build 3.1.0 containers - and be explicit on which Dockerfile each should build from
> Add Node-RED 3.1.0 containers

- helm/flowforge/templates/configmap.yaml
flowforge.yml was including fileStore key even if file-server disabled
> Only config file-server if needed

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/nodered-container.yml
To speed up the build and deployment process, concurrency in the pipelines has been enabled. As a result, only the latest change will be built and deployed while older pipelines, in the `in progress` state, will be cancelled.
> Enable concurrency in deployment pipelines

- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
- test/customizations.yml
- test/unit/configmap_spec.js
For https://github.com/FlowFuse/flowfuse/pull/2862
FlowFuse expects config file in below format:
```
telemetry:
enabled: true
frontend:
sentry:
dsn: 'https://URL-HERE.com'
production_mode: false
backend:
sentry:
dsn:  'https://URL-HERE.com'
```
https://github.com/FlowFuse/flowfuse/pull/2862
> Add support for configuring sentry telemetry

- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
- test/customizations.yml
- test/unit/configmap_spec.js
The application now features a [/metrics endpoint][1] for Prometheus to scrape. Since merging, the configuration file structure has been updated since through [another PR][2].
This change requires both changes to be in the application and afterwards allows enabling the endpoint and an engineer to configure scraping of the data.
[1]: https://github.com/FlowFuse/flowfuse/pull/2889
[2]: https://github.com/FlowFuse/flowfuse/pull/2893
> config: Add Prometheus config

- helm/flowforge/templates/deployment.yaml
PR introduces conditional creation of forge pod annotations required for proper metrics scrapping by prometheus.
> Add prometheus-related pod annotations

- helm/flowforge/templates/deployment.yaml
Fix annotations location within helm chart.
> Fix annotations location

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
Pin reusable workflows to tag instead of SHA
[#276](https://github.com/FlowFuse/CloudProject/issues/276)
> Pin reusable workflows to tag instead of SHA

- .github/workflows/nodered-container.yml
Push Node-RED images to the production ECR.
#207
> Push Node-RED images to production ECR

- .github/workflows/nodered-container.yml
Fix the typo in the environment name in Node-Red container build pipeline.
> FIX: typo in environment name in Node-Red container pipeline

- file-server/Dockerfile
- file-server/README.md
- flowforge-container/Dockerfile
- flowforge-container/README.md
Update FlowFuse containers to NodeJS 18 as NodeJS 16 is not receiving security updates any more.
Also updated the labels and the cosponsoring README.md files to FlowFuse
> Node 18 containers

- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/service-ingress.yaml
Allow to handle multiline ingress annotations.
#214
> FIX: Allow to handle multiline ingress annotations

- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
part of https://github.com/flowfuse/security/issues/31
Add support for setting the options to configure the Content Security Policy
https://github.com/flowfuse/security/issues/31
> Add support for setting Content Security Policy

- helm/flowforge/values.schema.json
This PR assures, that `forge.domain` value contains a valid domain name.
In result, installation without proper domain set will fail with:
```
Error: UPGRADE FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
flowforge:
- forge.domain: Does not match pattern '^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,6}$'
```
#226
> Validate value of `domain` property

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/nodered-container.yml
Use environment-scoped AWS credentials in pipelines
#208
> Use environment-scoped AWS credentials in pipelines

- .github/workflows/fileserver-container.yml
- file-server/package.json
Update the File Server contain to use the `@flowfuse` npm package.
**Note**: this should not be merged until https://github.com/FlowFuse/file-server/pull/86 is merged and I confirm we've done an initial publish of the package to the new scope.
> Update file server to new npm scope

- helm/flowforge/README.md
- helm/flowforge/templates/service-account.yaml
- helm/flowforge/values.schema.json
Increase configuration flexibility by adding a possibility to customise clusterrole name.
The reason for adding this feature is an attempt to install multiple FlowFuse apps on the same Kubernetes cluster. Since ClusterRole is a cluster-level object, the name must be unique.
> Add possibility to customise clusterrole name

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/nodered-container.yml
Enable container images security scan.
Should be merged after [#28](https://github.com/FlowFuse/github-actions-workflows/pull/28)
[#208](https://github.com/FlowFuse/CloudProject/issues/208)
> Enable image scanning for all containers

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/nodered-container.yml
This pull request fixes the tag version reference in the workflows file, updating it from `0.2.1` to `v0.2.1`.
[#208](https://github.com/FlowFuse/CloudProject/issues/208)
> FIX: workflows tag version reference

- .github/configs/cr.yaml
- .github/workflows/helm-chart-release.yaml
- .github/workflows/lint-pr.yaml
- .releaserc
This PR introduces a pipeline that will automatically release the flowfuse helm chart.
The pipeline performs:
* an analysis of commit messages to determine the type of release
* commit messages may follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) naming approach, however it is not required since it is forced on PR title
* the last version of the chart determined by the latest release tag
* release notes preparation based on commit messages
* chart version bump in `Chart.yaml`
* pack helm chart and update the index file
* publish the helm chart package in the `gh-pages` branch which triggers [GitHub Pages rebuild pipeline](https://github.com/FlowFuse/helm/actions/workflows/pages/pages-build-deployment) 
The pipeline is triggered on each push to the `main` …
> Introduce helm chart automatic release workflow

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/nodered-container.yml
This PR bumps reusable workflows to version v0.4.0 .
It should be merged after PR from the checklist.
> chore: Bump reusable workflows version to `v0.4.0`

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/nodered-container.yml
Bump workflows v4.0.1 due to minor bug in input values.
Depends on:
> chore: Update GitHub Actions workflows to use v0.4.1

- helm/flowforge/README.md
- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/file-storage.yml
- helm/flowforge/values.schema.json
This PR adds a possibility to configure Kubernetes resources for each container individually.
[#321](https://github.com/FlowFuse/CloudProject/issues/321)
[#322](https://github.com/FlowFuse/CloudProject/issues/322)
#264
#265
> feat: Allow to configure resources for each container

- helm/flowforge/README.md
- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/templates/service-ingress.yaml
- helm/flowforge/values.schema.json
This allows K8s to use cert-manager.io to issue TLS certs for both the core Forge apps and the Instances.
> Add support for using cert manager to issue TLS certs

- .github/workflows/build-containers.yml
part of FlowFuse/admin#212
Publish containers to both flowforge and flowfuse docker hub org name
FlowFuse/admin#212
> refactor: rename containers

- .github/workflows/build-containers.yml
Remove GH Action warnings for the build containers action.
> chore: Update actions used to build release containers

- helm/flowforge/README.md
- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/file-storage.yml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
This PR adds liveness, readiness and startup probes configuration for each pod. Additionally, liveness and readiness checks have been enabled by default for core and broker pods.
#266 
#263
> feat: Add possibility to configure probes for each pod

- helm/flowforge/README.md
- helm/flowforge/ci/ci-values.yaml
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/file-storage.yml
- helm/flowforge/templates/network-policy.yaml
- helm/flowforge/templates/secrets.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
- test/customizations.yml
This PR introduces following features:
* move sensitive data to kubernetes secret
* keep database connection parameters in single configuration block
* update README to match proposed changes
#283 
#268
> feat: Keep database credentials in kubernetes secrets

- .github/workflows/helm-chart.yml
This PR fixes file glob pattern for helm chart validation workflow trigger.
> ci: fix helm chart validation pipeline to include subdirectories

- .github/workflows/helm-chart.yml
This PR changes the way how checkov is performing helm chart scan. Instead of running a scan against a templated yaml file it is running directly in the helm chart directory.
> ci: Run checkov against helm chart directory instead of templated yaml

- .github/workflows/helm-chart.yml
This PR excludes sub-charts from the checkov scanning step in the Helm chart validation workflow.
> ci: Do not run checkov against subcharts

- helm/flowforge/README.md
- helm/flowforge/templates/_helpers.tpl
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/file-storage.yml
- helm/flowforge/templates/job-upgrade-db.yaml
- helm/flowforge/templates/secrets.yaml
This PR adds a possibility to provide database credentials as a Kubernetes secret created outside of the Helm chart.
#290
> feat: Add possibility to provide database credentials as an external secret

- helm/flowforge/README.md
This PR introduces `Upgrade` section in Helm chart documentation.
> chore: Create helm chart `upgrade` documentation

- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
part of FlowFuse/flowfuse#3324
Allows NR Pod log output to be enabled
FlowFuse/flowfuse#3324
> feat: Add log passthrough support

- helm/flowforge/templates/configmap.yaml
Forge app looks for `db.database` not `db.db`
reported in comment https://github.com/FlowFuse/helm/issues/268#issuecomment-1931671493
> fix: Fix typo missed in review

- helm/flowforge/templates/private-ca.yaml
While reviewing a different PR I noticed that the Node-RED project namespace version of the configmap didn't have a default name.
> fix: Ensure both priave ca certs configmaps have default names

- helm/flowforge/templates/job-upgrade-db.yaml
While testing OpenShift I noticed this job was getting run even if the `forge.fileStore.enabled` is false.
It was checking the wrong state
> fix: Only run the job if fileStore is enabled

- helm/flowforge/values.yaml
This pull request updates the local PostgreSQL image tag to `14.10.0-debian-11-r30`.
In result, from now on there is a possibility to schedule local database instance on ARM-based Kubernetes nodes.
https://github.com/FlowFuse/helm/issues/284
> feat: Allow to run local postgresql database on ARM nodes

- helm/flowforge/templates/_helpers.tpl
This PR applies old selector labeling approach and creates a workaround for the problem with immutable `spec.selector` field while running the deployment update with helm chart.
> fix: Rollback selector labels for existing deployments

- helm/flowforge/values.yaml
This pull request adds default container security context values for the broker container. Specifically, it sets `allowPrivilegeEscalation` to false and `readOnlyRootFilesystem` to true. These changes enhance the security of the broker container by preventing privilege escalation and ensuring that the root filesystem is read-only.
> feat: Add default container security context values for broker container

- helm/flowforge/README.md
- helm/flowforge/templates/file-storage.yml
- helm/flowforge/values.schema.json
Allows overriding the file store container
> feat: Allow FileStore image to be set

- helm/flowforge/README.md
- helm/flowforge/values.yaml
This pull request updates the liveness and readiness probe timeout values for the broker pod. The timeoutSeconds for both probes has been increased from 5 to 15, and the failureThreshold has been increased from 3 to 5. This change ensures that the broker pod has enough time to respond to the probes before being marked as unhealthy.
> fix: Update liveness and readiness probe timeout values for broker pod

- helm/flowforge/README.md
- helm/flowforge/templates/broker-ingress.yaml
- helm/flowforge/templates/broker.yaml
- helm/flowforge/tests/ingress_test.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
This pull request adds a possibility to configure unique annotations for forge and broker ingresses.
Additionally it also:
- moves broker ingress to separate file
- introduces basic unit tests for ingress objects created by the Helm chart
- updates documentation
https://github.com/FlowFuse/helm/issues/216
> feat: Add possibility to configure unique annotations for each ingress object

- .github/configs/chart-testing.yaml
- .github/workflows/helm-chart.yml
This PR extends the helm chart verification process by adding the upgrade step to the workflow. As a result, the helm chart from the particular PR is used for the upgrade process against deployment created with the helm chart from the `main` branch.
https://github.com/FlowFuse/helm/issues/315
> ci: Test helm chart upgrade process against version in `main` branch

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/nodered-container.yml
This pull request updates the workflows to version `v0.5.0`. It includes the following changes:
- Bump the version of the build_container_image workflow to `v0.5.0`
- Bump the version of the merge_multiarch_images workflow to `v0.5.0`
- Bump the version of the deploy_container_image workflow to `v0.5.0`
These updates ensure that the latest versions of the workflows are being used.
https://github.com/FlowFuse/github-actions-workflows/issues/31
> ci: Bump workflows to `v0.5.0`

- .github/workflows/helm-chart.yml
This PR adds a forge app image validation step to the Helm linting pipeline. It verifies if the latest application container image is available in the Docker Hub before executing the chart-testing tool.
This approach should solve the problem of unavailable application contaimer image during the release process.
https://github.com/FlowFuse/helm/issues/318
> ci: Wait for forge app public image to become available 

- helm/flowforge/templates/deployment.yaml
This PR adds a drop of all capabilities for init container. The main reasons of not making this parameter configurable are:
* init container does single, simple task which does not require capabilities to be modified 
* I am pretty sure that init container is a short term solution of how we are passing configuration parameters to the forge app and will not stay with us for a long time
I have tested such configuration locally and init container does its job as expected.
https://github.com/FlowFuse/CloudProject/issues/320
https://github.com/FlowFuse/CloudProject/issues/319
> fix: Drop all capabilities for init container

- helm/flowforge/values.yaml
This pull request adds the capability to drop all privileges in the container's security context. This is done by adding the "drop" capabilities to the containerSecurityContext section of the forge configuration. This change ensures that the container runs with minimal privileges, enhancing its security.
https://github.com/FlowFuse/CloudProject/issues/320
https://github.com/FlowFuse/CloudProject/issues/319
> feat: Drop all forge container capabilities

- helm/flowforge/templates/job-upgrade-db.yaml
This pull request fixes the image URL for the db-upgrade job in the Hlem chart. The image URL was incorrectly specified in the previous version, and this PR corrects it to use the correct format.
> fix: db-upgrade job image URL

- .github/workflows/helm-chart-release.yaml
This PR adds a possibility to manually trigger FlowFuse Helm chart release pipeline. Additionaly, it removes automatic pipeline trigger on push to the main branch.
> ci: Allow to manually trigger Helm chart release pipeline

- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/file-storage.yml
This PR adds the `imagePullPolicy: Always` property to the `initContainers` in the deployment YAML file. This ensures that the initContainers always pull the latest image when deploying the application.
https://github.com/FlowFuse/helm/issues/260
> feat: Add imagePullPolicy to initContainers

- .github/workflows/nodered-container.yml
- node-red-container/Dockerfile-4.0
This pull request adds a Dockerfile for Node-RED 4.0.0-beta.1-18 and build/upload workflows for building and uploading Node-RED 4.0.x container images.
https://github.com/FlowFuse/helm/issues/350
> ci: Introduce Node-RED `4.0.0-beta` container images

- .github/workflows/build-containers.yml
This PR adds a job responsible for creating and publishing on Docker Hub a container image with Node-RED `4.0.0-beta`.
https://github.com/FlowFuse/helm/issues/350
> ci: Add Node-RED 4.0 public container build job into existing workflow

- .github/workflows/build-containers.yml
32bit ARM builds failed to build for Node-RED 4.0 so their are no parent builds
> fix: Only build NR 4.0 for amd64 and arm64

- node-red-container/Dockerfile-3.1
Upstream docker images are still building as I type this but should be available shortly.
> chore: Update Dockerfile-3.1 for NR 3.1.8

- helm/flowforge/README.md
- helm/flowforge/templates/_helpers.tpl
- helm/flowforge/templates/broker-ingress.yaml
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
This PR adds the `forge.broker.domain` configuration option to allow running the MQTT broker on a custom domain. It also includes updates to the chart's schema and the documentation update.
The example of the FlowFuse Platform running with the broker on custom domain is available [here](https://3674.flowfuse.dev/).
Closes https://github.com/FlowFuse/helm/issues/295
> feat: Add possibility to customize domain for MQTT broker

- .github/workflows/helm-chart.yml
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/file-storage.yml
- helm/flowforge/templates/network-policy.yaml
- helm/flowforge/templates/private-ca.yaml
- helm/flowforge/templates/service-account.yaml
- helm/flowforge/templates/service-ingress.yaml
This PR ensures that all resources are properly bound to the namespace and remmediates CKV_K8S_21 checkov issue.
Additionally, the helm-chart.yml file has been updated to set the HELM_NAMESPACE environment due to the [ongoing checkov problem](https://github.com/bridgecrewio/checkov/issues/3910).
https://github.com/FlowFuse/helm/issues/250
> fix: Bind resources to the namespace

- .github/dependabot.yml
This pull request enables Dependabot for GitHub Actions. Dependabot is a tool that automatically checks for outdated dependencies and creates pull requests to update them. By enabling Dependabot for GitHub Actions, we ensure that our workflows are always using the latest versions of our dependencies.
> ci: Enable dependabot for GitHub Actions

- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/file-storage.yml
This pull request disables the `allowPrivilegeEscalation` setting for init containers. This change ensures that the init containers do not have the ability to escalate privileges, improving the security of the application.
https://github.com/FlowFuse/helm/issues/259
> feat: Disable `allowPrivilegeEscalation` for init containers

- .github/workflows/helm-chart-release.yaml
This pull request enhances the Helm chart release pipeline by integrating a step to wait for the completion of the container build workflow. This ensures that every released Helm chart points to an existing application container image. I opted for the API approach over [workflow_run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) for greater flexibility in building container images without automatically triggering the release of the Helm chart.
https://github.com/FlowFuse/admin/issues/301
> ci: Wait for container images build pipeline before running Helm chart release flow

- .github/workflows/helm-chart.yml
This pull request adds a conditional to the helm chart lint pipeline which skips advanced helm chart validation on the release. This change fixes the chicken-egg problem which appears during the release process when container images and Helm chart versions are updated within the same pull request ([example](https://github.com/FlowFuse/helm/actions/runs/8644285534/job/23699100785)).
> ci: Exclude advanced Helm chart validation on release

- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/file-storage.yml
This pull request disables the automounting of service account tokens in the broker and file-storage deployments. This change improves security by preventing unauthorized access to service account tokens.
https://github.com/FlowFuse/helm/issues/258
> fix: Disable automounting of service account tokens

- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/file-storage.yml
This pull request skips the CKV_K8S_35 check. 
The reason for skipping is that the current approach for injecting Kubernetes secret values into the application configuration is a temporary one and should be replaced with [a proper approach](https://github.com/FlowFuse/flowfuse/issues/3193) in the near future.
https://github.com/FlowFuse/helm/security/code-scanning/67
> fix: Temporarily skip CKV_K8S_35 for forge and file-server deployments

- helm/flowforge/templates/deployment.yaml
This pull request skips the CKV_K8S_35 check for forge deployment (missing one from https://github.com/FlowFuse/helm/pull/379) .
The reason for skipping is that the current approach for injecting Kubernetes secret values into the application configuration is a temporary one and should be replaced with https://github.com/FlowFuse/flowfuse/issues/3193 in the near future.
https://github.com/FlowFuse/helm/security/code-scanning/67
> fix: Add temporary annotation to skip CKV_K8S_35 check

- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/file-storage.yml
This pull request skips the CKV_K8S_10 and CKV_K8S_12 checks for the forge, file-server and broker deployments.
This is done because we do not want to apply default resource constraints that may not fit every environment. Additionally, it may slow down the application implementation process.
The cluster operator knows best what level of resources can be assigned to the application and should make such a decision independently. We are giving such a possibility via Helm chart values.
This is the follow-up of the [380](https://github.com/FlowFuse/helm/pull/380)
> fix: Skip CKV_K8S_10 and CKV_K8S_12 checks

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/nodered-container.yml
This pull request bumps the version of our internal reusable GitHub workflows to the `v0.10.0` . It allows the use of the latest version of actions used by the workflows.
> ci: Bump workflow versions to v0.10.0

- .releaserc
This line is pointing to a wrong path. https://github.com/FlowFuse/helm/blob/main/.releaserc#L28
Changelog file doesn't exist inside of that directory but in the root, that's why CHANGELOG doesn't get updated
#346
> ci: Fix CHANGELOG.md path in .releaserc

- .releaserc
This pull request reverts #385 .
As a result of above change
* CHANGELOG.md file was not part of the released Helm chart package 
* changelog was not generated properly for the Github Release
https://github.com/FlowFuse/helm/issues/346
> ci: revert "ci: Fix CHANGELOG.md path in .releaserc (#385)"

- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
partof FlowFuse/flowfuse#324
Allows Custom Hostname feature to be configured
partof FlowFuse/flowfuse#324
> feat: Add Custom Hostname config

- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
I missed a bit of config from the helm chart.
(if you know how to make forge.customHostname.cnameTarget required if forge.customerHostname.enabled = true that would be greate)
> fix: Add cnameTarget

- helm/flowforge/templates/configmap.yaml
This pull request fixex indentation within config map object related to custom hostnames feature.
> fix: indentation within custom hostname configuration

- .github/workflows/helm-chart-release.yaml
This pull request replaces `curl` with `gh` while gathering status of latest "Release container images" workflow run. Replacement of the commands is a quick solution for paginating api results.
> ci: check more than 100 workflow runs for status

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
This pull request updates fileserver and forge container deployment approach. It changes the way how updates to `flowfuse-values.yaml` files are pushed to the CloudProject repo. Instead of multiple pushes, single one is performed with all required changes.
https://github.com/FlowFuse/helm/issues/420
> ci: Update container images in single git push

- helm/flowforge/README.md
- helm/flowforge/templates/_helpers.tpl
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/secrets.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
This pull request extends the capabilities of FlowFuse Helm chart by adding a possibility to configure `nr-assistant`.
https://github.com/FlowFuse/helm/issues/425
> feat: introduce `nr-assistant` configuration

- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
Adds configuration options for persistent storage
https://github.com/FlowFuse/flowfuse/issues/4055
> feat: Add helm config for PersistentStorge

- .github/workflows/helm-chart-release.yaml
This pull request adds a step into "Release Helm Chart" workflow which ensures, that main CHANGELOG.md file will be updated after the release.
The script copies the approach from `admin` repo. However, since it compares last two releases, minor adjustments were made.
https://github.com/FlowFuse/helm/issues/346
> ci: Generate main changelog after Helm chart release

- .github/workflows/helm-chart-release.yaml
This PR adds missing push command withib `Update main changelog` step within `Release Helm Chart` workflow. 
https://github.com/FlowFuse/helm/issues/346
> ci: Push updated CHANGELOG.md

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
This pull request changes how images for FFC are built. Instead of multi-architecture image, only amd64 version is creatged.
https://github.com/FlowFuse/helm/issues/416
> ci: Build amd64 images only for FFC

- helm/flowforge/.helmignore
This pull request forces helm chart patch release.
Additionally, it adds `VERIONING.md` file to the list of helm ignored ones.
> fix: Add `VERSIONING.md` to helm ignored files

- helm/flowforge/README.md
- helm/flowforge/templates/file-storage-configmap.yaml
- helm/flowforge/templates/file-storage.yml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
This pull requests adds the possibility to enable `/metrics` endpoint with FileStore app metrics. Metrics can be consumed by a Prometheus instance.
> feat: Add possibility to configure Prometheus endpoint for FileStore app

- helm/flowforge/templates/file-storage.yml
This pull request sets proper value for `prometheus.io/port` annotation within `flowforge-file` deployment.
> fix: Set prometheus scrape port for `flowforge-file` to `3001`

- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
fixes #441 
Allow email debug to be enabled, mainly for the pre-staging env builds
#441
> fix: Add Email debug

- helm/flowforge/VERSIONING.md
Document mechanism and tools behind automatic calculation of Helm chart release number
> docs: Add release versioning documentation

- helm/flowforge/templates/configmap.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/private-ca.yaml
fixes #450
The deployment template was missing the default value for the private ca cert configmap
As was the flowforge.yml configmap.
#450
> fix: Ensure default private ca cert cm name

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/nodered-container.yml
This pull request updates the reusable workflows to the `v0.29.0` version.
In this particular version, the `build_container_image` workflow has been refactored. Starting from `v0.29.0` workflow builds a single architecture using the platform defined via `build_platform` input.
Additionally, the step responsible for building a multiarchitecture image has been removed, cutting down the time needed, to build the image.
closes https://github.com/FlowFuse/helm/issues/456
> ci: Bump containers reusable workflow version to `v0.29.0`

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/nodered-container.yml
This PR bumps reusable workflows to `v0.30.0`.
> ci: Bump reusable workflows to `v0.30.0`

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/nodered-container.yml
This pull request temporarily disable container images scanning with Trivy due to the [known issue](https://github.com/aquasecurity/trivy-action/issues/389).
> ci: temporarily disable container scan with Trivy

- helm/flowforge/README.md
- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/file-storage.yml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
This pull request adds a possibility to configure `priorityClassName` for all deployments created by this Helm chart.
Closes https://github.com/FlowFuse/helm/issues/481
> feat: Add possibility to apply `priorityClassName` to all deployments

- helm/flowforge/templates/emqx.yaml
This PR fixes the way how EMQX secret is created.
> fix: Change the way of handling EMQX secrets object

- helm/flowforge/templates/emqx.yaml
Move to supported way to add API tokens to broker.
This may break the dedicated instance already deployed, We may have to delete the emqx object before upgrading
> fix: Fix generating api secrets for Team Broker on deploy

- helm/flowforge/templates/_helpers.tpl
fixes #498
Allows for PostgreSQL existingSecret with AWS SES email
#498
> fix: Allow existingSecret for PostgreSQL and SES email

- helm/flowforge/README.md
- helm/flowforge/templates/_helpers.tpl
- helm/flowforge/templates/emqx-exporter-config.yaml
- helm/flowforge/templates/emqx-exporter.yaml
- helm/flowforge/templates/emqx.yaml
- helm/flowforge/tests/deployment_test.yaml
- helm/flowforge/tests/emqx-exporter_test.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
This pull request adds a possibility to deploy emqx-exporter with FlowFuse Helm chart.
Aditionally, it simplifies the logic behind checking the availability of APIs required by EMQX cluster.
https://github.com/FlowFuse/CloudProject/issues/559
> feat: add possibility to deploy emqx-exporter with FlowFuse helm chart

- helm/flowforge/README.md
- helm/flowforge/templates/broker.yaml
- helm/flowforge/tests/broker_test.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
fixes #502
Allow override on container image (to use local cache)
#502 502
> fix: Allow MQTT broker container config

- helm/flowforge/templates/emqx.yaml
Set it to 128MB (half max, but more then 1MB default)
https://docs.emqx.com/en/emqx/v5.8.2/hocon/#V-mqtt-S-mqtt-max_packet_size
FFC issues
> fix: Add default MQTT max packet

- .github/workflows/helm-chart.yml
- helm/flowforge/tests/broker_test.yaml
This pull request adds a job to `Helm chart validation` workflow responsible for running unit tests against FlowFuse Helm chart.
Tests are exected with `unittest` helm plugin.
Closes https://github.com/FlowFuse/helm/issues/507
> ci: Add helm chart unit tests to `Helm chart validation` workflow

- helm/flowforge/README.md
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/tests/deployment_test.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
This pull request separates the ingress annotations for the project's (NR instances) and the core application.
Custom annotations for NR instances can now be defined using the `forge.projectIngressAnnotation` variable.
To prevent breaking changes, the existing `ingress.annotations` will continue to be used as the value for the `INGRESS_ANNOTATIONS` environment variable within the core application if `forge.projectIngressAnnotation` is not defined.
Closes https://github.com/FlowFuse/helm/issues/475
> fix: Separate project's and core app ingress annotations

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
This pull request removes old deployment approach, which relies on updating pod's image tag directly on the kubernetes cluster, from core app and fileServer apps deployment workflows.
> chore(ci): Remove unused deployment jobs

- flowforge-container/Dockerfile
- flowforge-container/install-device-cache.sh
closes #519
Needs to be duplicated in the CI pipeline container build
#519
> feat: Add Node-RED client for device editor cache

- helm/flowforge/README.md
- helm/flowforge/templates/_helpers.tpl
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/templates/emqx.yaml
Allow team broker hostname to be set in the flowforge.yml
Defaults to `broker`.[forge.domain] 
(Also set EMQX config option)
> chore: Add config option for team broker hostname

- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/file-storage.yml
This pull requests adjusts the way how `securityContext` is created in each deployment managed by helm chart.
This change allows to provide no values for each `securityContext` . Since we provide pre-defined values for each of the deployment, now there will be a posibility to completly remove a `securityContenxt` values by assigining `null` value to the `forge.podSecurityContext`.
https://github.com/FlowFuse/helm/issues/526
> fix: Allow to set empty `securityContext` for all deployments

- helm/flowforge/README.md
- helm/flowforge/templates/file-storage-configmap.yaml
- helm/flowforge/values.yaml
This pull request adds a possibility to specify custom database name used by the File Storage service. 
Additionally, it removes hardcoded database username from the initialisation script.
https://github.com/FlowFuse/helm/issues/305
> feat: Allow File Storage database name to be customised  

- .github/workflows/helm-chart-release.yaml
This pull request improves the `Release Helm Chart` workflow by properly handling the `queued` status which can be returned by Github once requested the status of the `Release container images` pipeline.
Fixes https://github.com/FlowFuse/helm/issues/539
> ci: Do not fail Helm chart release if container images workflow returns `queued` status

- helm/flowforge/README.md
- helm/flowforge/templates/_helpers.tpl
- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/service-ingress.yaml
- helm/flowforge/tests/broker_test.yaml
- helm/flowforge/tests/service_test.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
This pull request adds possibility to create NodePort services for both forge and broker deployments. Additionally, it adds possibility to define static ports if NodePort serices is about to be created.
It also moves the logic responsible for handling selector labels for broker service to the helpers file.
Closes https://github.com/FlowFuse/flowfuse/issues/4041
> feat: Add possibility to create NodePort-type services for forge and broker deployments

- .github/workflows/build-containers.yml
This pull request extends `Release container images` by adding steps responsible for pushing Node-RED container images to FlowFuse private Elastic Container Registry.
Closes https://github.com/FlowFuse/CloudProject/issues/640
> ci: Add possibility to push Node-RED container images to private ECR

- helm/flowforge/templates/npm-registry.yaml
This pukk request fixes typo in flowfuse-npm-registry image use.
> fix: typo in `npmRegistry.image` reference

- .github/workflows/build-containers.yml
- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/helm-chart-release.yaml
- .github/workflows/helm-chart.yml
- .github/workflows/lint-pr.yaml
- .github/workflows/nodered-container.yml
- .github/workflows/test.yml
This pull request pins external GitHub Actions to commit hashes instead of tags in all workflows.
https://github.com/FlowFuse/CloudProject/issues/663
> chore: Pin external actions to commit hash

- helm/flowforge/templates/deployment.yaml
This pull request enables writable `/tmp` directory in forge pod by utilising `emptyDir` volume approach.
https://github.com/FlowFuse/flowfuse/pull/5367
> feat: Add writable `/tmp` directory for forge pod

- .github/workflows/build-containers.yml
- README.md
fixes FlowFuse/flowfuse#5361
Change the `flowfuse/node-red:latest` tag to point at the NR 4.0.x NodeJS 20 based containers.
Also fixes a README.md typo I spotted
FlowFuse/flowfuse#5361
> feat: Change the flowfuse/node-red:latest tag to Node-RED 4.0.x

- helm/flowforge/README.md
- helm/flowforge/templates/_helpers.tpl
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/templates/npm-registry.yaml
- helm/flowforge/values.schema.json
This pull requests generates private npm registry pasword if none is provided.
Closes https://github.com/FlowFuse/helm/issues/551
> feat: Remove hardcoded private npm registry credentials

- .github/workflows/helm-chart-release.yaml
This pull requests sets `skip_existing` parameter to `false` for `helm/chart-releaaser-action` to ensure, that both helm charts are uploaded.
https://github.com/FlowFuse/helm/issues/486
> fix:Disable skipping existing package release

- .github/workflows/helm-chart-release.yaml
This pull request removes deprecated token input from `azure/setup-helm` action in `Release Helm Chart` workflow.
> fix: Remove deprecated `token` parameter from `setup-helm` in `Release Helm Chart` workflow

- helm/flowfuse/README.md
- helm/flowfuse/templates/emqx.yaml
- helm/flowfuse/values.schema.json
- helm/flowfuse/values.yaml
This pull request adds the possibility to customise Team Broker images used by the broker deployment.
> feat: Add possibility to customise team broker image 

- file-server/Dockerfile
- flowforge-container/Dockerfile
This pull request updates base container images used to build forge and file-server containers to `node:20-alpine`
https://github.com/FlowFuse/flowfuse/issues/5403
> feat: Update base container images to `node:20-alpine`

- helm/flowfuse/values.yaml
This pull request changes default registry for `postgresql` image to `bitnamilegacy/postgresql` due to the changes described in linked issue.
closes https://github.com/FlowFuse/helm/issues/638
> fix: Switch to  `bitnamilegacy/postgresql` registry for local postgresql 
