- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/service-ingress.yaml
Also set node affinity for the management application
> Add ALB annotations

- helm/flowforge/templates/configmap.yaml
Matches up with https://github.com/flowforge/flowforge/pull/311
> Add default host config to 0.0.0.0

- CHANGELOG.md
- flowforge-container/package.json
- node-red-container/package.json
- Update CHANGELOG for 0.3.0
- Update version to 0.3.0
> Release 0.3.0

- helm/flowforge/Chart.yaml
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/network-policy.yaml
- helm/flowforge/templates/service-ingress.yaml
Also add a env var so the k8s driver knows where it's running
> Only apply ALB annotation on AWS

- helm/flowforge/Chart.yaml
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/network-policy.yaml
- helm/flowforge/templates/service-ingress.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
Fixes https://github.com/flowforge/flowforge-driver-k8s/issues#1
Fixes https://github.com/flowforge/flowforge-driver-k8s/issues#18
> Allow Project Node selector to be set

- helm/flowforge/templates/configmap.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/values.schema.json
Also allow admin to specify:
- Project Namespace
- Project Node Selector
- Management Node Selector
- Container Registry Credentials for private registries
> Add billing template to helm config

- CHANGELOG.md
- flowforge-container/package.json
- node-red-container/package.json
- Update CHANGELOG for 0.4.0
- Update version to 0.4.0
> Release 0.4.0

- CHANGELOG.md
- flowforge-container/package.json
- node-red-container/package.json
- Update CHANGELOG for 0.5.0
- Update version to 0.5.0
> Release 0.5.0

- CHANGELOG.md
- flowforge-container/package.json
- node-red-container/package.json
- Update CHANGELOG for 0.6.0
- Update version to 0.6.0
> Release 0.6.0

- flowforge-container/Dockerfile
Same as https://github.com/flowforge/docker-compose/pull/20
> Fix missing Python2 for sqlite3

- CHANGELOG.md
- flowforge-container/package.json
- node-red-container/package.json
- Update CHANGELOG for 0.7.0
- Update version to 0.7.0
> Release 0.7.0

- node-red-container/package.json
fixes #28
Adds dependency for @flowforge/nr-project-nodes
To be merged after @flowforge/nr-project-nodes are published to NPM
> add dep @flowforge/nr-project-nodes

- helm/flowforge/templates/broker.yaml
Make sure the paths are right in the mosquitto.conf file
> Update auth http paths

- CHANGELOG.md
- flowforge-container/package.json
- node-red-container/package.json
- Update CHANGELOG for 0.8.0
- Update version to 0.8.0
> Release 0.8.0

- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
> Add team types

- helm/flowforge/templates/configmap.yaml
Fix default broker service name
> Set correct default broker url

- helm/flowforge/README.md
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/values.schema.json
Also document more options that can be passed to the helm chart
> Add option to overide forge app container image

- CHANGELOG.md
- flowforge-container/package.json
- node-red-container/package.json
- Update CHANGELOG for 0.9.0
- Update version to 0.9.0
> Release 0.9.0

- CHANGELOG.md
- flowforge-container/package.json
- node-red-container/package.json
- Update CHANGELOG for 0.10.0
- Update version to 0.10.0
> Release 0.10.0

- helm/flowforge/README.md
- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/namespace.yaml
- helm/flowforge/templates/service-account.yaml
- helm/flowforge/values.yaml
The Forge container now runs as uid 1000 and can not use things like sudo
Also allows project namespace to be modified
fixes #52
> Limiting the containers capabilities

- .github/workflows/build-containers.yml
> Fix typo in build action

- .github/workflows/build-containers.yml
Pick up the right path to the README.md files
fixes #60
> Fix path to README

- helm/flowforge/README.md
`forge.projectsSelector` should be `forge.projectSelector`
> Typo in docs for ProjectSelector

- .github/workflows/build-containers.yml
- node-red-container/Dockerfile-2.2.x
Also tag all relevent containers as latest
fixes flowforge/docker-compose#54
> Build 2.2.x based stack container

- .github/workflows/build-containers.yml
fixes https://github.com/flowforge/docker-compose/issues/55
> Build for for 32bit Raspberry Pi

- flowforge-device-agent/Dockerfile
- flowforge-device-agent/README.md
> Expose the port so it can be used for HTTP-in/out

- README.md
- build-containers.sh
- helm/flowforge/README.md
- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/templates/file-storage.yml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
Also add file-server to build-contianers.sh
And fix some typos in the Helm Chart README.md
Add conditional requirements based on what's enabled
> Add enabled flags for broker and file-server

- .github/workflows/build-containers.yml
Make sure we check out all branches
> Fix helm chart publish

- index.yaml
> Fix typo in hostname

- helm/flowforge/templates/configmap.yaml
> Fix configmap

- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
- helm/flowforge/values.yaml
Allows the enabling of HubSpot support widget
fixes flowforge/CloudProject#16
- [-] Suitable unit/system level tests have been added and they pass
- [-] Upgrade instructions
- [-] Concepts
- [-] Backport needed? -> add the `backport` label
- [-] Includes a DB migration? -> add the `area:migration` label
> Add support for HubSpot support agent

- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
https://github.com/flowforge/flowforge/issues/1521
- [-] Suitable unit/system level tests have been added and they pass
- [-] Upgrade instructions
- [-] Concepts
- [-] Backport needed? -> add the `backport` label
- [-] Includes a DB migration? -> add the `area:migration` label
> Add support for Free trial configuration

- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
Adds support for the `branding` key in the flowforge.yml file
part of flowforge/flowforge#1591
> Add branding inserts

- helm/flowforge/templates/configmap.yaml
> Fix Go Template formating for frontend telemetry

- .gitignore
- test/customizations.yml
- test/unit/configmap_spec.js
- test/unit/helm_spec.js
- test/unit/ingres_spec.js
- test/unit/services_spec.js
- test/unit/setup.js
> Add more tests

- test/.eslintrc
- test/unit/configmap_spec.js
- test/unit/ingres_spec.js
- test/unit/services_spec.js
Adds our standard eslint rules for the test files
> Add eslint for test files

- .github/workflows/build-containers.yml
- node-red-container/Dockerfile-3.1
This currently targets 3.1.0-beta.2 and will need to be updated post 3.1.0 release
https://github.com/flowforge/CloudProject/issues/136
> Add NR 3.1.0 build

- helm/flowforge/README.md
part of #144
PostgreSQL can only be installed on x86_64 at the moment.
#144
> Add comment about PostgreSQL constraints

- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
When using an external DB allow connection to use SSL/TLS
part of #151
> Allow DB connection to use SSL

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/nodered-container.yml
Disable scheduled images build.
> Disable scheduled images build

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/nodered-container.yml
Build container images using packages from the public npm registry.
[210](https://github.com/flowforge/CloudProject/issues/210)
> Build container images using packages from public npm registry

- helm/flowforge/templates/file-storage.yml
- test/unit/configmap_spec.js
Turn on logging for the file-server
> Enable file server http logging

- helm/flowforge/templates/broker.yaml
part of https://github.com/FlowFuse/flowfuse/issues/2794
Increase cache timeout to 300s (5m)
https://github.com/FlowFuse/flowfuse/issues/2794
> Increase broker acl cache to 5mins

- helm/flowforge/README.md
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/values.schema.json
Allow flag so sentry knows where it's running.
https://github.com/FlowFuse/flowfuse/pull/2921
> Add SENTRY_ENV to deployment

- helm/flowforge/templates/deployment.yaml
- helm/flowforge/templates/file-storage.yml
part of https://github.com/FlowFuse/CloudProject/issues/264
Add NODE_ENV to the forge app
https://github.com/FlowFuse/CloudProject/issues/264
> Set NODE_ENV

- .github/workflows/nodered-container.yml
Fix typo in image upload step which might lead to some confusions.
> FIX: typo in upload step name

- helm/flowforge/templates/broker.yaml
- helm/flowforge/templates/deployment.yaml
- helm/flowforge/values.schema.json
Add affinity configuration for broker and flowforge deployments.
#204
> Add affinity configuration for broker and flowforge deployments

- helm/flowforge/README.md
Fix typo in README.md regarding affinity field.
> Fix typo in README.md

- .github/workflows/flowforge-container.yml
- flowforge-container/package.json
Depends on https://github.com/FlowFuse/driver-k8s/pull/126 and then my publishing an initial version to npm.
> Update k8s driver package scope

- node-red-container/Dockerfile-3.1
Update NR container to 3.1.2.
The NR containers are still building at the point in time I'm raising this PR... make sure they are done before merging
> Update NR to 3.1.2

- .github/workflows/flowforge-container.yml
- README.md
- file-server/Dockerfile
- flowforge-container/Dockerfile
- flowforge-container/package.json
- node-red-container/Dockerfile
- node-red-container/Dockerfile-2.2.x
- node-red-container/Dockerfile-3.1
Updates the FlowFuse contain to install `@flowfuse/flowfuse`.
Depends on https://github.com/FlowFuse/flowfuse/pull/3190 being merged and initial package published.
> Update for new flowfuse npm package

- helm/flowforge/README.md
> fix: improve the description of the forge.registry field

- .github/workflows/test.yml
- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
part of FlowFuse/flowfuse#3474
Adds support to configure the Google Analytics support
FlowFuse/flowfuse#3474
> feat: Add support for Google Analytics

- .github/workflows/build-containers.yml
Fix version of build-push action to point to existing action
> fix: Fix docker/build-push action version

- node-red-container/Dockerfile-3.1
Bump 3.1.x to latest NR version
> fix: Update Dockerfile-3.1 to 3.1.5

- .github/workflows/fileserver-container.yml
- .github/workflows/flowforge-container.yml
- .github/workflows/nodered-container.yml
This PR updates containers build/deploy reusable workflows to `v0.5.1`.
> ci: Update containers build/deploy reusable workflows to `v0.5.1`

- node-red-container/Dockerfile-3.1
part of https://github.com/FlowFuse/CloudProject/issues/367
> Update to NR 3.1.6

- helm/flowforge/ci/full-stack-values.yaml
This pull request adds validation for full-stack deployment with Helm chart.
> ci: Validate Helm chart against full stack deployment

- file-server/package.json
- flowforge-container/package.json
- helm/flowforge/Chart.yaml
- node-red-container/package.json
> feat: Release 2.2.0

- flowforge-container/package.json
- helm/flowforge/Chart.yaml
- node-red-container/Dockerfile-4.0
Includes NR 4.0-beta.2 container
> chore: Bump for 2.4.2 release

- node-red-container/Dockerfile-3.1
This is so device agents bound to an instance on Windows will pick up the latest version with the npm.cmd fix.
> chore: Update 3.1.x container to use NR 3.1.9

- node-red-container/Dockerfile-4.0
Note the base NR container is still build as I raise this. Ensure that exists before merging.
> chore: Update Dockerfile-4.0 to pick 4.0.0-beta.3

- node-red-container/Dockerfile-4.0
Bump NR 4 beta to the .3-1 repackage
> chore: Bump nr beta version

- node-red-container/Dockerfile-4.0
Upstream containers still building as I raise this - just getting things lined up.
> chore: Bump NR 4 for beta.4

- CHANGELOG.md
This pull request updates the CHANGELOG.md file for the 2.7.0 helm chart release.
> chore: Changelog for the `2.7.0` helm chart release

- node-red-container/Dockerfile-3.1
Update to use the new container versions
> chore: Bump NR 3.1 version

- node-red-container/Dockerfile-3.1
Merge once https://github.com/node-red/node-red-docker/actions/runs/9565287644 is complete
> chore: Update NR container to 3.1.11

- node-red-container/Dockerfile-4.0
> chore: Update Dockerfile-4.0 for 4.0.1 release

- .github/workflows/fileserver-container.yml
This pull request fixex typo made in the git configuration step.
> ci: typo fix in git configuration

- node-red-container/Dockerfile-4.0
> chore: update nr docker to 4.0.2

- CHANGELOG.md
This pull request updates the main changelog to the release `2.10.0`.
> chore: Update the main changlog for `2.10.0` release

- node-red-container/Dockerfile
- node-red-container/Dockerfile-2.2.x
- node-red-container/Dockerfile-3.1
- node-red-container/Dockerfile-4.0
Workaround for FlowFuse/flowfuse#4037
> chore: rebrand working directory

- helm/flowforge/README.md
- helm/flowforge/templates/configmap.yaml
- helm/flowforge/values.schema.json
part of https://github.com/FlowFuse/flowfuse/issues/4201
Allows Session expiry to be configured
https://github.com/FlowFuse/flowfuse/issues/4201
> feat: Allow Session limits to be set

- helm/flowforge/README.md
> fix: Update README.md

- node-red-container/Dockerfile-3.1
- node-red-container/Dockerfile-4.0
Bump for new NR base containers
Wait for Node-RED 3.1.12 containers to build before merging
> chore: bump Node-RED containers

- node-red-container/Dockerfile-3.1
- node-red-container/Dockerfile-4.0
Update to NR 4.0.5 and NR 3.1.14
Keeping in draft until containers all ready
> chore: Update for new Node-RED releases

- helm/flowforge/templates/emqx.yaml
This PR fixes EMQX service templates
> fix: EMQX service templates

- helm/flowforge/templates/emqx.yaml
Tune the EMQX HTTP Auth settings to handle connection storms better
> fix: Tune EMQX HTTP Auth settings

- .github/workflows/helm-chart-release.yaml
- CHANGELOG.md
This pull request refines how ‘main’ changelog entries are collected and ensures that each commit is considered, regardless of how it was introduced into the main branch.
Additionally, it adds previously committed changelog entries.
Closes https://github.com/FlowFuse/helm/issues/501
> chore(ci): Improve changelog entry collection and add missing entries

- helm/flowforge/templates/broker.yaml
This PR changs the way how and when `flowforge-broker` service is created.
> fix: creation of flowforge-broker service

- .github/workflows/helm-chart-release.yaml
- CHANGELOG.md
This pull reuqest fixes the typo in the script responsible for generating main changelog content.
Additionally, it adds missing changelog entries.
> ci: Fix typo in changelog update script

- node-red-container/Dockerfile-4.0
> chore: Bump to NR 4.0.7

- helm/flowforge/README.md
> docs: Add OpenShift to cloudProvider docs

- node-red-container/Dockerfile-4.0
> chore: Bump Stack Container to Node-RED 4.0.9

- flowforge-container/install-device-cache.sh
Add NR 4.0.9 to device agent cache
> chore: Add NR 4.0.9 to device agent cache

- helm/flowforge/templates/npm-registry.yaml
> fix: npm registry auth config 

- flowforge-container/Dockerfile
fixes #561
Adds git to the container
#561
> feat: Add git command line tool

- helm/flowfuse/Chart.yaml
This pull request updates `name` and `keywords` fields in `Chart.yaml` file for `flowfuse` helm chart.
https://github.com/FlowFuse/helm/issues/486
> fix: Update name and keywords in `chart.yaml` for flowfuse chart

- helm/flowforge/Chart.yaml
- helm/flowforge/templates/NOTES.txt
This pull request rollback previously announced `flowforge` chart depreciation.
https://github.com/FlowFuse/helm/issues/486
> fix: Rollback flowforge chart depreciation
